### ISSUE TITLE
Home page jumbotron on mobile

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#12]
The text columns are too narrow, and it's unreadable and extending the hero image too far down the page. See mobile comp for expected layout.

If we need to reduce the size of the subhead copy in order to make that work, let's look at doing that.

https://drive.google.com/file/d/12cbVWhnO7Y-YnaPGV83dIKvH-nwxQZDz/view?usp=sharing

Jason's comment:
This is mostly fixed, except the subhead copy is going all the way to the edge when the screen size is 920 and below. Looks like we just need to add some padding to the right side.

Moving this ticket into the backlog

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved I will msg when I push

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved in the current build

**Comment by pguevara65** [comment]
@cmoosman1 thank you!

@jthiel16 can you please review?

cc: @NoelWormwood

**Comment by jthiel16** [comment]
@cmoosman1 This looks much better at the smallest mobile sizes now, but same issue is still happening on medium screens (between 760 and 920px wide), where the subhead text is going off screen on the right side.

cc: @NoelWormwood @pguevara65

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved in the current build

**Comment by pguevara65** [comment]
@cmoosman1 thanks!

@jthiel16 can you please review

cc: @NoelWormwood

**Comment by jthiel16** [comment]
Looks good, thanks Criss
