### ISSUE TITLE
On all interior pages, the gray div in the jumbotron area is looking too wide (and going off the screen) when viewing on medium-sized desktop screen

### ISSUE THREAD

**Issue by NoelWormwood** [Tallwave/Sargon-QA#2]

**Comment by cmoosman1** [comment]
@NoelWormwood - This should be resolved in the current build

**Comment by NoelWormwood** [comment]
@jthiel16 Please QA and confirm

**Comment by jthiel16** [comment]
@NoelWormwood @cmoosman1 Yep, the gray bar width looks good now. Between 1470 and 1570, the intro text/heading is being pushed over to the left a bit too far though

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved in the current build.

**Comment by NoelWormwood** [comment]
@jthiel16 Please QA

**Comment by jthiel16** [comment]
@cmoosman1 I'm still seeing the text alignemnt issue between 1470px and 1570px
